### ISSUE TITLE
nnn does not quit properly when running preview-tui in tmux

### ISSUE THREAD

**Issue by stubkan** [jarun/nnn#1063]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 20.04
- [x] Desktop Environment: Cinnamon
- [x] Terminal Emulator: cool-retro-term, terminal
- [ ] Shell:
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: tmux new-session -A -s nnn "nnn -Pp"
- [ ] Configuration options set:
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Using tmux to start a tmux session as the loading step to run nnn with preview-tui plugin

tmux new-session "nnn -Pp"
also occurs when I run it with
tmux new-session -A -s nnn "nnn -Pp"

The program works great, but quitting it fails and has to be force quit with ctrl+shift+q or a ctrl+c break, I think this is related to ;

#901
and
#900

Can provide further information if needed.

**Comment by luukvbaal** [comment]
This should have been fixed by https://github.com/jarun/nnn/commit/5533f152bd9f23bc26c4673b587d111003e76422. Try `getplugs master`.

**Comment by stubkan** [comment]
I did the thing ;
curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh

sadly, the issue still remains. Where are the plugins located? I will try manually replacing the file

**Comment by luukvbaal** [comment]
Plugins are located  `$XDG_CONFIG_HOME/nnn/plugins`. You can run `$XDG_CONFIG_HOME_nnn/plugins/getplugs master`.

**Comment by stubkan** [comment]
Good news, manually replaced the preview-tui plugin file and it now correctly quits.

I'm guessing the update plugins script doesn't overwrite plugins so that is maybe an issue.

**Comment by luukvbaal** [comment]
It will prompt you to replace but you have to provide it `master` as an argument to update to the latest versions available on the master branch...
