### ISSUE TITLE
Too many args [-nw -s t]

### ISSUE THREAD

**Issue by UnicodeAlt255** [jarun/nnn#179]
Running 2.2.r1.g243f8c6-1 on Arch Linux

Running `nnn` gives me the output: `Too many args [-nw -s t]`

**Comment by jarun** [comment]
Please read the release notes. Either your EDITOR or PAGER or SHELL variable has multiple arguments. From v2.2 `nnn` supports one combined argument.

**Comment by jarun** [comment]
Release notes: https://github.com/jarun/nnn/releases/tag/v2.2

**Comment by jarun** [comment]
To debug, you can:

```
echo $EDITOR
echo $PAGER
echo $SHELL
```

and figure out which one is leading to this issue.

**Comment by UnicodeAlt255** [comment]
You're right, but how can I change it to a "combined argument"?
I forgot that my `$EDITOR` is set to `emacsclient -nw -s t`.

**Comment by jarun** [comment]
For now, does dropping `-s t` work for you?
I will have to work on it as I can see.

**Comment by UnicodeAlt255** [comment]
Well the whole point of `emacsclient -nw -s t` is to open up a client of a emacs daemon called "t", it allows me to quickly open up emacs to edit something without waiting for the whole startup every time. Without the multiple arguments this would no longer be possible, unless I'm missing something.

**Comment by jarun** [comment]
OK. I have to repeat myself - I will have to work on it as I can see.

**Comment by UnicodeAlt255** [comment]
Thank you so much! Unfortunately I still get the same result despite the commit.

**Comment by jarun** [comment]
Here's what I see with _latest master_: https://asciinema.org/a/219797

Works as expected.

See what VISUAL/EDITOR shows in your help and config screen.

**Comment by jarun** [comment]
Your problem is the second line. Try:

    export EDITOR="emacsclient -nw -s t"

Works for me (I used VISUAL): https://asciinema.org/a/219799

**Comment by jarun** [comment]
If you are having further issues, please debug yourself. It's very taxing for me to check and fix local issues.

**Comment by Enlik** [comment]
There is a regression after the change.

```bash
echo blabla > 'lol; touch classic'
./nnn
```

1. navigate to file, press e
2. enjoy file 'classic' being created :)

Please, avoid `sh -c` as much as possible.

**Comment by jarun** [comment]
@Enlik what would you suggest to meet both the ends?

**Comment by Enlik** [comment]
Splitting manually words in EDITOR should work.

On thing to consider: when it comes to delimiters, I don't know if it's necessary to handle all from IFS or such (not sure if it's documented and supposed to work across shells in the same way).

**Comment by Enlik** [comment]
In both bash and fish, in `less`, after setting an editor command with `\t`, when `v` is pressed (in less it opens the file for editing), \t delimiters the editor from the argument.

Not that it should be common to put \t there…

**Comment by Enlik** [comment]
If you want to keep it very simple, as another idea add a guard if you quote with just `'`:

(pseudocode)

```
bool is_path_safe(path):
   if path contains '
     return false
   else
     return true

# then

spawn_editor(path):
   quoted = ' + path + '
   if not is_path_safe(quoted):
     return nope
  else
    $EDITOR quoted
```

**Comment by jarun** [comment]
I am working on quoting 'editor file' completely.

**Comment by jarun** [comment]
Fixed at commit 5df231947392475ced257a6ba5e4cec3c3fbb5a9.

**Comment by Enlik** [comment]
Works for me too. Thank you!

**Comment by UnicodeAlt255** [comment]
Still not working for me, I'll try to figure it out later.
https://asciinema.org/a/TxcMBj6wqAzuy1eZQjF9k7Q9h

**Comment by jarun** [comment]
I think I understand the issue. :+1: 

The check for VISUAL/EDITOR is removed in master. However, the restriction of a single combined argument stays on PAGER and SHELL. Please check your PAGER and SHELL variables.

**Comment by UnicodeAlt255** [comment]
For me, `PAGER` is not set, and `SHELL` is `/usr/bin/fish`.

**Comment by jarun** [comment]
OK. It's not possible for you to get the error `Too many args [-nw -s t]` for VISUAL/EDITOR because the relevant function is not called for VISUAL/EDITOR on latest master. Either:

- you are not on latest master, or,
- you have not compiled it

**Comment by UnicodeAlt255** [comment]
Ah, yeah you were right, I forgot to compile after pulling. It works now.
